import { readFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { JSDOM, VirtualConsole } from "jsdom";
import { beforeAll, describe, expect, it, vi } from "vitest";

/**
 * The landing page, tested as the file a browser is actually served.
 *
 * It is generated by scripts/build-notes.ts, so nothing here reads the Markdown. Three things
 * about it are load-bearing and none of them is visible in a unit test of a function:
 *
 *   - with no JavaScript it still shows the title, the sentence and the index, because the
 *     animation is the only part of it that needs a script;
 *   - it delegates the seven experiments to page 6 rather than listing them, which is only safe
 *     while page 6 actually links all seven;
 *   - the disclaimer is on it, because this is the first page and guardrail 1 says a beginner is
 *     told the crowd is invented before they read a number.
 */

const WEB = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const LANDING = join(WEB, "index.html");
const GENERATED = join(WEB, "generated");

const EXPERIMENT_IDS = [
  "e1-push-strength",
  "e2-density",
  "e3-robot-speed",
  "e4-recovery",
  "e5-propagation",
  "e6-perception",
  "e7-politeness",
];

function landingDocument(): Document {
  const html = readFileSync(LANDING, "utf8");
  return new JSDOM(html).window.document;
}

function linkTargets(document: Document, selector: string): string[] {
  const targets: string[] = [];
  for (const anchor of Array.from(document.querySelectorAll<HTMLAnchorElement>(selector))) {
    targets.push(anchor.getAttribute("href") ?? "");
  }
  return targets;
}

describe("the landing page", () => {
  beforeAll(() => {
    if (!existsSync(LANDING)) {
      throw new Error(
        "web/index.html is missing. Run `npm run notes` first — this suite tests the generated " +
          "landing page, not the Markdown.",
      );
    }
  });

  it("says what it is in one sentence", () => {
    const standfirst = landingDocument().querySelector(".standfirst")?.textContent ?? "";
    const text = standfirst.replace(/\s+/g, " ").trim();
    expect(text.length).toBeGreaterThan(0);
    // One terminal stop, at the end. The previous standfirst was four sentences and read as a
    // summary of the site rather than an invitation into it.
    expect(text).toMatch(/^[^.?!]+[.?!]$/);
    // The line that tells the intended reader they are welcome.
    expect(text).toContain("no robotics background");
  });

  it("offers exactly one way in, and it goes to page 1", () => {
    const document = landingDocument();
    const starts = linkTargets(document, ".start-link");
    expect(starts).toEqual(["./generated/the-room.html"]);
  });

  it("keeps the index to eleven links and lists no experiment page", () => {
    const document = landingDocument();
    const links = linkTargets(document, ".contents a");
    expect(links.length).toBe(11);
    for (const id of EXPERIMENT_IDS) {
      expect(links).not.toContain(`./generated/${id}.html`);
    }
  });

  it("reaches every numbered page and the instrument", () => {
    const document = landingDocument();
    const links = linkTargets(document, ".contents a");
    const manifest = JSON.parse(readFileSync(join(GENERATED, "pages.json"), "utf8")) as {
      id: string;
      isExperiment: boolean;
    }[];
    for (const page of manifest) {
      if (page.isExperiment) {
        continue;
      }
      expect(links).toContain(`./generated/${page.id}.html`);
    }
    expect(links).toContain("./instrument.html");
  });

  it("delegates the seven experiments to the page that explains what an experiment is", () => {
    // The landing page dropped them on the strength of this. If page 6 ever stops linking one,
    // that page is an orphan and this is where it shows up.
    const html = readFileSync(join(GENERATED, "experiments.html"), "utf8");
    const document = new JSDOM(html).window.document;
    const links = linkTargets(document, "a");
    for (const id of EXPERIMENT_IDS) {
      expect(links).toContain(`./${id}.html`);
    }
  });

  it("tells a beginner the crowd is invented, on the first page they see", () => {
    const document = landingDocument();
    const footer = document.querySelector(".page-footer")?.textContent ?? "";
    expect(footer).toContain("Everything here is simulated");
    const caption = document.querySelector(".hero-caption")?.textContent ?? "";
    expect(caption).toContain("invented crowd");
  });

  it("hides the animation until a script fills it", async () => {
    // The whole no-JavaScript guarantee for this page is one attribute. Statically the figure is
    // hidden; the module reveals it only once it has a canvas to draw into. Here it has none, so
    // the reader is left with the title, the sentence and the index rather than an empty box.
    const html = readFileSync(LANDING, "utf8");
    expect(html).toContain("<figure class=\"hero\" id=\"hero\" hidden>");

    const dom = new JSDOM(html, { pretendToBeVisual: true, virtualConsole: new VirtualConsole() });
    const globals = globalThis as unknown as Record<string, unknown>;
    globals["window"] = dom.window;
    globals["document"] = dom.window.document;
    globals["HTMLElement"] = dom.window.HTMLElement;
    globals["requestAnimationFrame"] = (): number => 0;

    vi.resetModules();
    await import("../../hero.js");

    const figure = dom.window.document.getElementById("hero");
    expect(figure?.hidden).toBe(true);
    expect(dom.window.document.querySelector(".contents a")).not.toBeNull();
  });
});
