import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import type { PairedRun } from "../../contracts/pairedRun.js";
import { makePairedRun } from "../../contracts/pairedRun.js";
import { makeScene } from "../../contracts/scene.js";
import type { Trajectory } from "../../contracts/trajectory.js";
import { makeTrajectory } from "../../contracts/trajectory.js";
import {
  ade,
  adeBetweenClouds,
  fde,
  fdeBetweenClouds,
  frechet,
} from "../divergence/index.js";
import { cvmResidual, paired } from "../estimator/index.js";
import type { PermutationSource } from "../null/splitHalf.js";
import { splitHalfNull } from "../null/splitHalf.js";

/**
 * The seam that makes "Python is the oracle" mechanical rather than aspirational.
 *
 * Fixtures are generated by `mirn fixtures`, committed, and diffed in CI. Two failures are
 * distinguishable by design: a stale fixture shows up as a git diff of the golden JSON when CI
 * regenerates it, and drift shows up here, naming the subject, the case, the quantity and the
 * tolerance the oracle author declared.
 *
 * Three families arrive with three different case shapes, so a subject's entry point is a
 * function from one case to a list of (quantity, ours, theirs) triples rather than a bare
 * `(a, b) => number`. That is what lets the split-half subject check every individual split as
 * well as the floor those splits are quantiled into: a floor that happened to land in the right
 * place on wrong splits would otherwise pass.
 */

// Resolved from this file, not from cwd: the Vite root is `web/`, so cwd differs between a
// direct `vitest` run and a run through the workspace, and a cwd-relative path silently breaks.
const FIXTURE_DIR = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "..",
  "..",
  "tests",
  "golden",
  "parity",
);

interface Fixture {
  readonly schemaVersion: number;
  readonly subject: string;
  readonly tolerance: { readonly kind: "relative" | "exact"; readonly value: number };
  readonly cases: readonly RawCase[];
}

/** Only `id` is common across the three families; each runner narrows the rest itself. */
interface RawCase {
  readonly id: string;
}

/** One quantity the oracle pinned, and what this side computed for it. */
interface Comparison {
  readonly quantity: string;
  readonly actual: number;
  readonly expected: number;
}

type Runner = (testCase: RawCase) => readonly Comparison[];

interface DivergenceCase extends RawCase {
  readonly a: readonly number[];
  readonly b: readonly number[];
  readonly expected: number;
}

interface AgentCase {
  readonly agentId: string;
  readonly agentUid: number;
  readonly treated: readonly number[];
  readonly control: readonly number[];
}

interface EstimatorCase extends RawCase {
  readonly dt: number;
  readonly robot: readonly number[];
  readonly agents: readonly AgentCase[];
  readonly expected: number;
  readonly horizonSteps?: number;
  readonly endStep?: number;
}

interface NullCase extends RawCase {
  readonly dt: number;
  readonly paths: readonly (readonly number[])[];
  readonly permutations: readonly (readonly number[])[];
  readonly strideSteps: number;
  readonly alpha: number;
  readonly expectedSamples: readonly number[];
  readonly expectedMean: number;
  readonly expected: number;
}

function divergenceRunner(compute: (a: Float64Array, b: Float64Array) => number): Runner {
  return (testCase: RawCase): readonly Comparison[] => {
    const divergenceCase = testCase as DivergenceCase;
    const actual = compute(
      Float64Array.from(divergenceCase.a),
      Float64Array.from(divergenceCase.b),
    );
    return [{ quantity: "value", actual, expected: divergenceCase.expected }];
  };
}

/**
 * Rebuild the oracle's `RolloutPair` from the literal arrays, through the real factories.
 *
 * Going through `makePairedRun` rather than hand-assembling an object is the point: a fixture
 * that dodged the contract could carry arms the product would refuse to measure, and the parity
 * number would be for a scene that cannot occur.
 */
function pairFromCase(estimatorCase: EstimatorCase): PairedRun {
  const treatedPedestrians: Trajectory[] = [];
  const controlPedestrians: Trajectory[] = [];
  for (const agent of estimatorCase.agents) {
    treatedPedestrians.push(
      makeTrajectory({
        agentId: agent.agentId,
        agentUid: agent.agentUid,
        positions: Float64Array.from(agent.treated),
        t0: 0,
        dt: estimatorCase.dt,
      }),
    );
    controlPedestrians.push(
      makeTrajectory({
        agentId: agent.agentId,
        agentUid: agent.agentUid,
        positions: Float64Array.from(agent.control),
        t0: 0,
        dt: estimatorCase.dt,
      }),
    );
  }

  const robot = makeTrajectory({
    agentId: "robot",
    agentUid: -1,
    positions: Float64Array.from(estimatorCase.robot),
    t0: 0,
    dt: estimatorCase.dt,
  });

  const sceneId = `parity_${estimatorCase.id}`;
  const treated = makeScene({
    sceneId,
    pedestrians: treatedPedestrians,
    robot,
    robotPresent: true,
    source: "fixture",
    seed: 0,
  });
  const control = makeScene({
    sceneId,
    pedestrians: controlPedestrians,
    robot: null,
    robotPresent: false,
    source: "fixture",
    seed: 0,
  });
  return makePairedRun({ treated, control, treatment: { kind: "robot-presence" } });
}

function pairedRunner(testCase: RawCase): readonly Comparison[] {
  const estimatorCase = testCase as EstimatorCase;
  const estimate = paired(pairFromCase(estimatorCase));
  return [{ quantity: "value", actual: estimate.value, expected: estimatorCase.expected }];
}

function cvmResidualRunner(testCase: RawCase): readonly Comparison[] {
  const estimatorCase = testCase as EstimatorCase;
  const horizonSteps = estimatorCase.horizonSteps;
  const endStep = estimatorCase.endStep;
  if (horizonSteps === undefined || endStep === undefined) {
    throw new Error(
      `cvm_residual case '${estimatorCase.id}' must carry horizonSteps and endStep; a window ` +
        `left implicit would be measured at the end of the episode, where a parked crowd makes ` +
        `the residual exactly zero and the comparison vacuous`,
    );
  }
  const estimate = cvmResidual(pairFromCase(estimatorCase), horizonSteps, endStep);
  return [{ quantity: "value", actual: estimate.value, expected: estimatorCase.expected }];
}

function splitHalfRunner(testCase: RawCase): readonly Comparison[] {
  const nullCase = testCase as NullCase;

  const paths: Float64Array[] = [];
  for (const path of nullCase.paths) {
    paths.push(Float64Array.from(path));
  }

  // The splits come from the fixture, never from `seededPermutations`. numpy's PCG64 cannot be
  // reproduced here without reimplementing a numpy internal, so the two languages agree on the
  // partition by being handed it, and what is actually under test is the cloud arithmetic.
  const permutations: PermutationSource = (
    nPedestrians: number,
    splitIndex: number,
  ): Int32Array => {
    const row = nullCase.permutations[splitIndex];
    if (row === undefined || row.length !== nPedestrians) {
      throw new Error(
        `fixture case '${nullCase.id}' has no ${nPedestrians}-entry permutation for split ` +
          `${splitIndex}`,
      );
    }
    return Int32Array.from(row);
  };

  const result = splitHalfNull(
    paths,
    nullCase.permutations.length,
    permutations,
    nullCase.alpha,
    nullCase.strideSteps,
  );

  const comparisons: Comparison[] = [];
  for (let splitIndex = 0; splitIndex < nullCase.expectedSamples.length; splitIndex++) {
    comparisons.push({
      quantity: `sample[${splitIndex}]`,
      actual: result.samples[splitIndex] as number,
      expected: nullCase.expectedSamples[splitIndex] as number,
    });
  }
  comparisons.push({ quantity: "mean", actual: result.mean, expected: nullCase.expectedMean });
  comparisons.push({ quantity: "floor", actual: result.floor, expected: nullCase.expected });
  return comparisons;
}

/**
 * Every subject the oracle exports must resolve to an entry point here. A missing one is a
 * FAILURE, not a skip — that is what stops "we will port it later" from being silent, and it
 * mirrors the Python side's own `test_every_registered_divergence_has_a_card` gate.
 */
const ENTRY_POINTS: Readonly<Record<string, Runner>> = {
  "divergence.ade.between_paths": divergenceRunner(ade),
  "divergence.fde.between_paths": divergenceRunner(fde),
  "divergence.frechet.between_paths": divergenceRunner(frechet),
  "divergence.ade.between_clouds": divergenceRunner(adeBetweenClouds),
  "divergence.fde.between_clouds": divergenceRunner(fdeBetweenClouds),
  "estimator.paired.per_run": pairedRunner,
  "estimator.cvm_residual.per_run": cvmResidualRunner,
  "calibration.split_half_null.floor": splitHalfRunner,
};

function loadFixtures(): readonly Fixture[] {
  const names = readdirSync(FIXTURE_DIR).filter((name) => name.endsWith(".json")).sort();
  return names.map((name) => JSON.parse(readFileSync(join(FIXTURE_DIR, name), "utf8")) as Fixture);
}

const fixtures = loadFixtures();

describe("cross-language parity with the Python oracle", () => {
  it("found fixtures at all", () => {
    // A silently empty fixture directory would make every parity assertion below vacuous.
    expect(fixtures.length).toBeGreaterThan(0);
  });

  it("has a TypeScript entry point for every subject the oracle exports", () => {
    const missing = fixtures
      .map((fixture) => fixture.subject)
      .filter((subject) => ENTRY_POINTS[subject] === undefined);
    expect(missing).toEqual([]);
  });

  for (const fixture of fixtures) {
    describe(fixture.subject, () => {
      const run = ENTRY_POINTS[fixture.subject];

      it("is a schema version this test understands", () => {
        expect(fixture.schemaVersion).toBe(2);
      });

      for (const testCase of fixture.cases) {
        it(`reproduces case '${testCase.id}' within the declared tolerance`, () => {
          expect(run).toBeDefined();
          const comparisons = (run as Runner)(testCase);
          // A runner that silently produced nothing would report green for a case it never ran.
          expect(comparisons.length).toBeGreaterThan(0);

          for (const comparison of comparisons) {
            if (fixture.tolerance.kind === "exact") {
              // The Frechet canary. If this ever fails the cause is a logic difference, never
              // rounding, because its DP has no accumulation in it.
              expect(comparison.actual).toBe(comparison.expected);
              continue;
            }

            const scale = Math.max(Math.abs(comparison.expected), 1e-12);
            const relative = Math.abs(comparison.actual - comparison.expected) / scale;
            if (relative > fixture.tolerance.value) {
              throw new Error(
                `parity drift in ${fixture.subject} case '${testCase.id}' ` +
                  `(${comparison.quantity}):\n` +
                  `  oracle   ${comparison.expected}\n` +
                  `  browser  ${comparison.actual}\n` +
                  `  relative ${relative} exceeds the fixture's declared ` +
                  `${fixture.tolerance.value}\n` +
                  `  regenerate with: .venv/bin/python -m mirn.cli fixtures --out ` +
                  `tests/golden/parity`,
              );
            }
          }
        });
      }
    });
  }
});
