import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
  ade,
  adeBetweenClouds,
  fde,
  fdeBetweenClouds,
  frechet,
} from "../divergence/index.js";

/**
 * The seam that makes "Python is the oracle" mechanical rather than aspirational.
 *
 * Fixtures are generated by `mirn fixtures`, committed, and diffed in CI. Two failures are
 * distinguishable by design: a stale fixture shows up as a git diff of the golden JSON when CI
 * regenerates it, and drift shows up here, naming the subject, the case, and the tolerance the
 * oracle author declared.
 */

// Resolved from this file, not from cwd: the Vite root is `web/`, so cwd differs between a
// direct `vitest` run and a run through the workspace, and a cwd-relative path silently breaks.
const FIXTURE_DIR = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "..",
  "..",
  "tests",
  "golden",
  "parity",
);

interface Fixture {
  readonly schemaVersion: number;
  readonly subject: string;
  readonly tolerance: { readonly kind: "relative" | "exact"; readonly value: number };
  readonly cases: readonly {
    readonly id: string;
    readonly a: readonly number[];
    readonly b: readonly number[];
    readonly expected: number;
  }[];
}

/**
 * Every subject the oracle exports must resolve to an entry point here. A missing one is a
 * FAILURE, not a skip — that is what stops "we will port it later" from being silent, and it
 * mirrors the Python side's own `test_every_registered_divergence_has_a_card` gate.
 */
const ENTRY_POINTS: Readonly<Record<string, (a: Float64Array, b: Float64Array) => number>> = {
  "divergence.ade.between_paths": ade,
  "divergence.fde.between_paths": fde,
  "divergence.frechet.between_paths": frechet,
  "divergence.ade.between_clouds": adeBetweenClouds,
  "divergence.fde.between_clouds": fdeBetweenClouds,
};

function loadFixtures(): readonly Fixture[] {
  const names = readdirSync(FIXTURE_DIR).filter((name) => name.endsWith(".json")).sort();
  return names.map((name) => JSON.parse(readFileSync(join(FIXTURE_DIR, name), "utf8")) as Fixture);
}

const fixtures = loadFixtures();

describe("cross-language parity with the Python oracle", () => {
  it("found fixtures at all", () => {
    // A silently empty fixture directory would make every parity assertion below vacuous.
    expect(fixtures.length).toBeGreaterThan(0);
  });

  it("has a TypeScript entry point for every subject the oracle exports", () => {
    const missing = fixtures
      .map((fixture) => fixture.subject)
      .filter((subject) => ENTRY_POINTS[subject] === undefined);
    expect(missing).toEqual([]);
  });

  for (const fixture of fixtures) {
    describe(fixture.subject, () => {
      const compute = ENTRY_POINTS[fixture.subject];

      it("is a schema version this test understands", () => {
        expect(fixture.schemaVersion).toBe(1);
      });

      for (const testCase of fixture.cases) {
        it(`reproduces case '${testCase.id}' within the declared tolerance`, () => {
          expect(compute).toBeDefined();
          const actual = (compute as (a: Float64Array, b: Float64Array) => number)(
            Float64Array.from(testCase.a),
            Float64Array.from(testCase.b),
          );

          if (fixture.tolerance.kind === "exact") {
            // The Frechet canary. If this ever fails the cause is a logic difference, never
            // rounding, because its DP has no accumulation in it.
            expect(actual).toBe(testCase.expected);
            return;
          }

          const scale = Math.max(Math.abs(testCase.expected), 1e-12);
          const relative = Math.abs(actual - testCase.expected) / scale;
          if (relative > fixture.tolerance.value) {
            throw new Error(
              `parity drift in ${fixture.subject} case '${testCase.id}':\n` +
                `  oracle   ${testCase.expected}\n` +
                `  browser  ${actual}\n` +
                `  relative ${relative} exceeds the fixture's declared ${fixture.tolerance.value}\n` +
                `  regenerate with: .venv/bin/python -m mirn.cli fixtures --out tests/golden/parity`,
            );
          }
        });
      }
    });
  }
});
