import { fail } from "../core/errors.js";
import type { Scene } from "./scene.js";
import { pedestrianById } from "./scene.js";
import type { Trajectory } from "./trajectory.js";

export type ArmId = "treated" | "control";

/**
 * What the two arms differ by.
 *
 * Python's `RolloutPair` hard-codes the intervention: factual has a robot, counterfactual does
 * not. The teaching product needs the same machinery for "with the shove / without the shove",
 * where the robot is present in BOTH arms and the robot's own trajectory is what is compared.
 * `{ kind: "robot-presence" }` reproduces Python's semantics exactly; the other kinds are new.
 * One mechanism, two lessons.
 */
export type TreatmentSpec =
  | { readonly kind: "none" }
  | { readonly kind: "robot-presence" }
  | { readonly kind: "disturbance"; readonly disturbanceId: string };

/**
 * A treated scene and its control twin. Mirrors `RolloutPair`, generalised.
 *
 * This pairing is the whole experiment: both arms share a seed, share exogenous noise, and differ
 * only in the treatment.
 */
export interface PairedRun {
  readonly kind: "pairedRun";
  readonly treated: Scene;
  readonly control: Scene;
  readonly treatment: TreatmentSpec;
  readonly seed: number;
  readonly nSteps: number;
}

export function makePairedRun(init: {
  treated: Scene;
  control: Scene;
  treatment: TreatmentSpec;
}): PairedRun {
  const { treated, control, treatment } = init;

  if (treated.seed !== control.seed) {
    fail(
      "PairedRun violates 'treated.seed === control.seed': " +
        `${treated.seed} != ${control.seed}`,
    );
  }

  if (treatment.kind === "robot-presence") {
    if (treated.robotPresent !== true) {
      fail(
        "PairedRun violates 'treated.robotPresent is true' under a robot-presence treatment: " +
          `got ${treated.robotPresent}`,
      );
    }
    if (control.robotPresent !== false) {
      fail(
        "PairedRun violates 'control.robotPresent is false' under a robot-presence treatment: " +
          `got ${control.robotPresent}`,
      );
    }
  } else if (treated.robotPresent !== control.robotPresent) {
    fail(
      `PairedRun with treatment '${treatment.kind}' must have the robot in the same state in ` +
        `both arms; only a robot-presence treatment may differ on it`,
    );
  }

  const treatedIds = new Set<string>();
  for (const pedestrian of treated.pedestrians) {
    treatedIds.add(pedestrian.agentId);
  }
  const controlIds = new Set<string>();
  for (const pedestrian of control.pedestrians) {
    controlIds.add(pedestrian.agentId);
  }
  if (treatedIds.size !== controlIds.size) {
    fail(
      "PairedRun violates 'identical pedestrian agentId sets': " +
        `treated=${[...treatedIds].sort().join(",")} control=${[...controlIds].sort().join(",")}`,
    );
  }
  for (const agentId of treatedIds) {
    if (!controlIds.has(agentId)) {
      fail(
        "PairedRun violates 'identical pedestrian agentId sets': " +
          `treated=${[...treatedIds].sort().join(",")} control=${[...controlIds].sort().join(",")}`,
      );
    }
  }

  let nSteps: number | null = null;
  for (const agentId of [...treatedIds].sort()) {
    const treatedTrajectory = pedestrianById(treated, agentId);
    const controlTrajectory = pedestrianById(control, agentId);

    if (treatedTrajectory.dt !== controlTrajectory.dt) {
      fail(
        `PairedRun violates 'identical dt' for shared agent '${agentId}': ` +
          `${treatedTrajectory.dt} != ${controlTrajectory.dt}`,
      );
    }

    // STRICTER THAN PYTHON, deliberately. contracts.py allows 1e-9 because third-party adapters
    // have to be accommodated. Here both arms come out of one function against one noise tape, so
    // any difference at all at t=0 means the tape leaked arm state — which is precisely the bug a
    // tolerance would hide.
    if (
      treatedTrajectory.positions[0] !== controlTrajectory.positions[0] ||
      treatedTrajectory.positions[1] !== controlTrajectory.positions[1]
    ) {
      fail(
        `PairedRun violates 'identical first position exactly' for shared agent '${agentId}': ` +
          `treated=(${treatedTrajectory.positions[0]}, ${treatedTrajectory.positions[1]}) ` +
          `control=(${controlTrajectory.positions[0]}, ${controlTrajectory.positions[1]})`,
      );
    }

    // Also stricter than Python, which does not check it at all. Both arms are generated by one
    // call over a fixed tick count, so unequal length is a bug rather than an adapter quirk.
    if (treatedTrajectory.nSteps !== controlTrajectory.nSteps) {
      fail(
        `PairedRun violates 'identical nSteps' for shared agent '${agentId}': ` +
          `${treatedTrajectory.nSteps} != ${controlTrajectory.nSteps}`,
      );
    }
    if (nSteps === null) {
      nSteps = treatedTrajectory.nSteps;
    } else if (treatedTrajectory.nSteps !== nSteps) {
      fail(
        `PairedRun requires every agent to share nSteps, got ${treatedTrajectory.nSteps} for ` +
          `'${agentId}' against ${nSteps} for the others`,
      );
    }
  }

  if (nSteps === null) {
    fail("PairedRun requires at least one shared pedestrian");
  }

  return Object.freeze({
    kind: "pairedRun" as const,
    treated,
    control,
    treatment,
    seed: treated.seed,
    nSteps,
  });
}

/** (treated, control) pairs ordered by agentId, matching `RolloutPair.paired_agents`. */
export function pairedAgents(pair: PairedRun): readonly (readonly [Trajectory, Trajectory])[] {
  const agentIds: string[] = [];
  for (const pedestrian of pair.treated.pedestrians) {
    agentIds.push(pedestrian.agentId);
  }
  agentIds.sort();

  const pairs: (readonly [Trajectory, Trajectory])[] = [];
  for (const agentId of agentIds) {
    pairs.push([pedestrianById(pair.treated, agentId), pedestrianById(pair.control, agentId)]);
  }
  return pairs;
}
